import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from fpdf import FPDF
from dotenv import load_dotenv

load_dotenv()

class PlantReportPDF(FPDF):
    def header(self):
        # Add Logo Watermark/Branding
        # More robust path for Vercel:
        curr_dir = os.path.dirname(os.path.abspath(__file__))
        logo_path = os.path.join(curr_dir, "assets", "logo.png")
        
        if os.path.exists(logo_path):
            # Place logo in top right
            self.image(logo_path, 170, 8, 25)
            
            # Central faint watermark (using image with transparency if possible, 
            # but fpdf2 handles it via alpha in image or just placing it)
            # Since fpdf2 simple image doesn't do alpha easily without PIL, we just place it.
            # We'll place it in the center.
            self.set_alpha(0.1) # Set transparency
            self.image(logo_path, 60, 100, 90)
            self.set_alpha(1.0) # Reset transparency
        else:
            print(f"WARNING: Logo not found at {logo_path}")
        
        self.set_font('Helvetica', 'B', 15)
        self.set_text_color(46, 125, 50) # GreenMind Green
        self.cell(0, 10, 'GreenMind AI - Analysis Report', 0, 1, 'L')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by GreenMind AI Expert Systems', 0, 0, 'C')

def generate_pdf_report(result, output_path):
    pdf = PlantReportPDF()
    pdf.add_page()
    
    plant = result.get("plant", "Unknown Plant")
    disease = result.get("disease", "Unknown Condition")
    confidence = result.get("confidence", "N/A")
    description = result.get("description", "")
    cause = result.get("cause", "")
    solution = result.get("solution", "")

    # Main Status Header
    pdf.set_font('Helvetica', 'B', 20)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 15, plant, 0, 1, 'L')
    
    pdf.set_font('Helvetica', 'B', 14)
    if disease.lower() == "healthy":
        pdf.set_text_color(46, 125, 50)
    else:
        pdf.set_text_color(211, 47, 47)
    pdf.cell(0, 10, f"Status: {disease}", 0, 1, 'L')
    
    pdf.set_font('Helvetica', '', 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, f"Confidence Score: {confidence}", 0, 1, 'L')
    pdf.ln(5)

    # Detailed Findings
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(46, 125, 50)
    pdf.cell(0, 10, "  Detailed Findings", 0, 1, 'L', fill=True)
    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 7, description)
    pdf.ln(5)

    # Cause
    pdf.set_fill_color(255, 249, 196) # Light yellow
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(130, 119, 23)
    pdf.cell(0, 10, "  Possible Cause", 0, 1, 'L', fill=True)
    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(0, 0, 0)
    pdf.multi_cell(0, 7, cause)
    pdf.ln(5)

    # Solution
    pdf.set_fill_color(232, 245, 233) # Light green
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(27, 94, 32)
    pdf.cell(0, 10, "  Treatment Plan", 0, 1, 'L', fill=True)
    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(27, 94, 32)
    pdf.multi_cell(0, 7, solution)

    # Add a watermark-like logo in center if possible (optional, already in header)
    # For a true watermark, we could add a large faint logo here but fpdf2 opacity is complex
    
    pdf.output(output_path)
    return output_path

def send_analysis_report(receiver_email, result):
    smtp_server = os.getenv("EMAIL_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("EMAIL_PORT", "587"))
    sender_email = os.getenv("EMAIL_USER")
    sender_password = os.getenv("EMAIL_PASSWORD")

    if not sender_email or not sender_password or "your-email" in sender_email:
        print(f"ERROR: Email credentials not fully configured. User: {sender_email}")
        return False

    # Gmail App Passwords usually have spaces, but SMTP needs them stripped
    if sender_password:
        sender_password = sender_password.replace(" ", "")

    plant = result.get("plant", "Unknown Plant")
    disease = result.get("disease", "Unknown Condition")
    confidence = result.get("confidence", "N/A")
    description = result.get("description", "")
    cause = result.get("cause", "")
    solution = result.get("solution", "")
    
    is_healthy = disease.lower() == "healthy"
    status_color = "#2e7d32" if is_healthy else "#d32f2f"
    bg_gradient = "linear-gradient(135deg, #2e7d32 0%, #1b5e20 100%)"

    message = MIMEMultipart("alternative")
    message["Subject"] = f"🌿 Analysis Ready: {plant} ({disease})"
    message["From"] = f"GreenMind AI <{sender_email}>"
    message["To"] = receiver_email

    html_content = f"""
    <html>
    <head>
        <style>
            .card {{
                background: #ffffff;
                border-radius: 16px;
                padding: 24px;
                margin-bottom: 20px;
                box-shadow: 0 4px 12px rgba(0,0,0,0.05);
            }}
            .badge {{
                display: inline-block;
                padding: 6px 12px;
                border-radius: 20px;
                font-size: 12px;
                font-weight: bold;
                text-transform: uppercase;
                letter-spacing: 1px;
            }}
        </style>
    </head>
    <body style="margin: 0; padding: 0; background-color: #f8faf9; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">
        <div style="max-width: 600px; margin: 40px auto; overflow: hidden;">
            
            <!-- PREMIUM HEADER -->
            <div style="background: {bg_gradient}; padding: 40px 20px; text-align: center; border-radius: 24px 24px 0 0;">
                <div style="color: rgba(255,255,255,0.8); font-size: 12px; font-weight: bold; letter-spacing: 2px; text-transform: uppercase; margin-bottom: 8px;">GreenMind AI</div>
                <h1 style="color: #ffffff; margin: 0; font-size: 28px; font-weight: 300;">Analysis <span style="font-weight: bold;">Report</span></h1>
            </div>

            <!-- CONTENT CONTAINER -->
            <div style="padding: 20px; background: #f8faf9; border-radius: 0 0 24px 24px; border: 1px solid #eee; border-top: none;">
                
                <!-- MAIN STATUS CARD -->
                <div class="card" style="text-align: center; border-top: 4px solid {status_color};">
                    <div style="font-size: 48px; margin-bottom: 10px;">{'🌿' if is_healthy else '⚠️'}</div>
                    <h2 style="margin: 0; color: #1a1a1a; font-size: 22px;">{plant}</h2>
                    <p style="color: {status_color}; font-weight: bold; font-size: 18px; margin: 10px 0;">{disease}</p>
                    <div class="badge" style="background: #e3f2fd; color: #1976d2;">Confidence: {confidence}</div>
                </div>

                <!-- DESCRIPTION SECTION -->
                <div class="card">
                    <h3 style="color: #2e7d32; margin-top: 0; font-size: 16px;">Detailed Findings</h3>
                    <p style="color: #4a4a4a; line-height: 1.6; font-size: 14px; margin-bottom: 0;">{description}</p>
                </div>

                <!-- TWO COLUMN GRID (Mockup for Cause/Solution) -->
                <div class="card" style="background: #fff9c4; border-left: 4px solid #fbc02d;">
                    <h3 style="color: #827717; margin-top: 0; font-size: 14px; text-transform: uppercase;">Possible Cause</h3>
                    <p style="color: #333; font-size: 14px; margin-bottom: 0;">{cause}</p>
                </div>

                <div class="card" style="background: #e8f5e9; border-left: 4px solid #2e7d32;">
                    <h3 style="color: #1b5e20; margin-top: 0; font-size: 14px; text-transform: uppercase;">Treatment Plan</h3>
                    <p style="color: #1b5e20; font-size: 14px; line-height: 1.6; margin-bottom: 0;">{solution}</p>
                </div>

                <!-- FOOTER -->
                <div style="text-align: center; padding: 20px; color: #999; font-size: 12px;">
                    <p>Designed by GreenMind AI Expert Systems</p>
                    <p>You received this because you requested a plant analysis via our mobile app.</p>
                </div>
            </div>
        </div>
    </body>
    </html>
    """

    part = MIMEText(html_content, "html")
    message.attach(part)

    # --- PDF ATTACHMENT ---
    import tempfile
    temp_pdf = os.path.join(tempfile.gettempdir(), f"Report_{plant.replace(' ', '_')}.pdf")
    try:
        generate_pdf_report(result, temp_pdf)
        with open(temp_pdf, "rb") as attachment:
            pdf_part = MIMEBase("application", "octet-stream")
            pdf_part.set_payload(attachment.read())
        
        encoders.encode_base64(pdf_part)
        pdf_part.add_header(
            "Content-Disposition",
            f"attachment; filename= {os.path.basename(temp_pdf)}",
        )
        message.attach(pdf_part)
        print(f"DEBUG: Attached PDF report to email.")
    except Exception as pdf_err:
        print(f"WARNING: Could not generate or attach PDF: {pdf_err}")

    try:
        print(f"DEBUG: Connecting to SMTP {smtp_server}:{smtp_port}...")
        with smtplib.SMTP(smtp_server, smtp_port, timeout=20) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.sendmail(sender_email, receiver_email, message.as_string())
        
        # Cleanup temp PDF
        if os.path.exists(temp_pdf):
            try: os.remove(temp_pdf)
            except: pass
            
        print(f"SUCCESS: Premium email with PDF sent to {receiver_email}")
        return True
    except smtplib.SMTPAuthenticationError:
        print("ERROR: SMTP Authentication failed. Check your EMAIL_USER and EMAIL_PASSWORD (App Password).")
        return False
    except Exception as e:
        print(f"ERROR: Failed to send premium email to {receiver_email}: {type(e).__name__}: {e}")
        return False
